/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mahasiswa;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author StartX
 */
public class Mahasiswa extends javax.swing.JFrame {
    
    /**
     * Creates new form Mahasiswa
     */
    public Mahasiswa() {
        initComponents();
            tampilan();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vtabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus_data = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        txtcaridata = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnim = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbjurusan = new javax.swing.JComboBox();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vtabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Alamat", "Jurusan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vtabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vtabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(vtabel);
        vtabel.getColumnModel().getColumn(0).setResizable(false);
        vtabel.getColumnModel().getColumn(1).setResizable(false);
        vtabel.getColumnModel().getColumn(2).setResizable(false);
        vtabel.getColumnModel().getColumn(3).setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setText("Cari data berdasarkan NIM :");

        btn_tambah.setText("Tambah Data");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit Data");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_hapus_data.setText("Hapus Data");
        btn_hapus_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_dataActionPerformed(evt);
            }
        });

        btn_refresh.setText("Refresh Data");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        txtcaridata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcaridataActionPerformed(evt);
            }
        });
        txtcaridata.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtcaridataInputMethodTextChanged(evt);
            }
        });

        jLabel3.setText("Jurusan");

        jLabel4.setText("Alamat");

        cmbjurusan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TI", "SK", "SI" }));

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });

        jLabel2.setText("NIM :");

        jLabel5.setText("Nama :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus_data, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(8, 8, 8))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtalamat)
                            .addComponent(txtnama)
                            .addComponent(txtnim, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtcaridata, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah)
                    .addComponent(btn_edit)
                    .addComponent(btn_hapus_data)
                    .addComponent(btn_refresh)
                    .addComponent(txtcaridata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
          
        String nim,nama,jurusan,alamat;
        try {
            nim = txtnim.getText();
            nama = txtnama.getText();
            jurusan = String.valueOf(cmbjurusan.getSelectedItem());
            alamat = txtalamat.getText();
            if (nim.trim().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Nim belum diisi");
                txtnim.requestFocus();
            }else if(nama.trim().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Nama belum diisi");
                txtnama.requestFocus();
            }else if(jurusan.equals("")){
                JOptionPane.showMessageDialog(rootPane, "Pilih Jurusan");
                cmbjurusan.requestFocus();
            }else if(alamat.trim().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Alamat belum diisi");
                txtalamat.requestFocus();
            }else {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection cn = DriverManager.getConnection("jdbc:odbc:mahasiswa","root","stikomdbjambi");
            String sql = "Insert into tb_mhs (nim,nm_mhs,jurusan,alamat) values('"+nim+"','"+nama+"','"+jurusan+"','"+alamat+"')";
            Statement st = cn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Data mahasiswa dengan NIM " + nim + "Berhasil disimpan");
            bersihkan();
            tampilan();
            }
        } catch (Exception err) {
            err.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Gagal simpan data");
            tampilan();
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        /* Ini perintah pindah kelas
        *edit_mhs edit = new edit_mhs();
        *edit.setLocationRelativeTo(edit);
        *edit.show();
        */
                String nim1, nama1, jurusan1, alamat1;
        try {
            nim1 = txtnim.getText();
            nama1 = txtnama.getText();
            jurusan1 = String.valueOf(cmbjurusan.getSelectedItem());
            alamat1 = txtalamat.getText();

            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection cn = DriverManager.getConnection("jdbc:odbc:mahasiswa", "", "");
            String sql = "UPDATE tb_mhs SET nm_mhs='"+nama1+"',jurusan='"+jurusan1+"',"
                    + "alamat='"+alamat1+"' "+ "WHERE nim='"+nim1+"'";
            Statement st = cn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Data mahasiswa dengan NIM " + nim1 + "Telah diupdate");
            bersihkan();
            tampilan();

        } catch (Exception err) {
            err.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Update data gagal");
            tampilan();
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapus_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_dataActionPerformed
        // TODO add your handling code here:
        //delete_mhs hapus = new delete_mhs();
        //hapus.setLocationRelativeTo(hapus);
        //hapus.show();
        String nim;
        try {
            nim = txtnim.getText();
            

            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection cn = DriverManager.getConnection("jdbc:odbc:mahasiswa","","");
            String sql = "DELETE FROM tb_mhs WHERE nim='" + nim + "'";
            Statement st = cn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Mahasiswa dengan NIM " + nim + "telah dihapus");
            bersihkan();
            tampilan();
        } catch (Exception err) {
            err.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Data gagal dihapus");
            tampilan();
        }
    }//GEN-LAST:event_btn_hapus_dataActionPerformed

    private void txtcaridataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcaridataActionPerformed
        // TODO add your handling code here:
        String cari;
        cari=txtcaridata.getText();
       DefaultTableModel tabMode;
        this.getContentPane().setLayout(null);
        vtabel.setToolTipText("Tabel Mahasiswa");
        Object [] row = {"NIM","Nama","Jurusan","Alamat"};
        tabMode=new DefaultTableModel(null,row);
        vtabel.setModel(tabMode);
         try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection cn = DriverManager.getConnection("jdbc:odbc:mahasiswa", "", "");
            Statement st = cn.createStatement();
            String sql = "SELECT * FROM tb_mhs where nim like '%" + cari +"%'";
            ResultSet set = st.executeQuery(sql);
            while(set.next()){
                String nim = set.getString("nim");
                String nama = set.getString("nm_mhs");
                String jurusan = set.getString("jurusan");
                String alamat=set.getString("alamat");
                String [] data = { nim,nama,jurusan,alamat};
                tabMode.addRow(data);
                JOptionPane.showMessageDialog(rootPane, "Data ditemukan");
            }
         } catch (Exception err) {
             err.printStackTrace();
             JOptionPane.showMessageDialog(rootPane, "Data tidak ditemukan");
         }
    }//GEN-LAST:event_txtcaridataActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        tampilan();
        txtcaridata.setText("");
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed

    private void vtabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vtabelMouseClicked
        // TODO add your handling code here:
        int baris = vtabel.getSelectedRow();
        //int kolom = vtabel.getSelectedColumn();
        String nim = vtabel.getValueAt(baris, 0).toString();
        txtnim.setText(nim);
        String nama = vtabel.getValueAt(baris, 1).toString();
        txtnama.setText(nama);
        String jurusan = vtabel.getValueAt(baris, 2).toString();
        //cmbjurusan.getSelectedObjects(jurusan);
        String alamat = vtabel.getValueAt(baris, 3).toString();
        txtalamat.setText(alamat);
    }//GEN-LAST:event_vtabelMouseClicked

    private void txtcaridataInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtcaridataInputMethodTextChanged
        // TODO add your handling code here:
       String cari;
        cari=txtcaridata.getText();
       DefaultTableModel tabMode;
        this.getContentPane().setLayout(null);
        vtabel.setToolTipText("Tabel Mahasiswa");
        Object [] row = {"NIM","Nama","Jurusan","Alamat"};
        tabMode=new DefaultTableModel(null,row);
        vtabel.setModel(tabMode);
         try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection cn = DriverManager.getConnection("jdbc:odbc:mahasiswa", "", "");
            Statement st = cn.createStatement();
            String sql = "SELECT * FROM tb_mhs where nim like '%" + cari +"%'";
            ResultSet set = st.executeQuery(sql);
            while(set.next()){
                String nim = set.getString("nim");
                String nama = set.getString("nm_mhs");
                String jurusan = set.getString("jurusan");
                String alamat=set.getString("alamat");
                String [] data = { nim,nama,jurusan,alamat};
                tabMode.addRow(data);
                JOptionPane.showMessageDialog(rootPane, "Data ditemukan");
            }
         } catch (Exception err) {
             err.printStackTrace();
             JOptionPane.showMessageDialog(rootPane, "Data tidak ditemukan");
         }
    }//GEN-LAST:event_txtcaridataInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         * 
         */
        
        //JTable vtabel;
        //vtabel.setCellSelectionEnabled(true);
        //ListSelectionModel celSelectionModel=vtabel.getSelectionModel();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Mahasiswa().setVisible(true);
                Mahasiswa nj = new Mahasiswa();
                nj.setLocationRelativeTo(nj);
                nj.setVisible(true);
                
            }
        });
    }
     public void tampilan(){
        DefaultTableModel tabMode;
        this.getContentPane().setLayout(null);
        vtabel.setToolTipText("Tabel Mahasiswa");
        Object [] row = {"NIM","Nama","Jurusan","Alamat"};
        tabMode=new DefaultTableModel(null,row);
        vtabel.setModel(tabMode);
        vtabel.getSelectedRows();
         try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection cn = DriverManager.getConnection("jdbc:odbc:mahasiswa", "root", "stikomdbjambi");
            Statement st = cn.createStatement();
            String sql = "SELECT * FROM tb_mhs order by nim";
            ResultSet set = st.executeQuery(sql);
            while(set.next()){
                String nim = set.getString("nim");
                String nama = set.getString("nm_mhs");
                String jurusan = set.getString("jurusan");
                String alamat=set.getString("alamat");
                String [] data = { nim,nama,jurusan,alamat};
                tabMode.addRow(data);
              
            }
         } catch (Exception err) {
             err.printStackTrace();;
             
         }
         
         
  }
     public void bersihkan(){
        txtnim.setText("");
        txtnama.setText("");
        cmbjurusan.requestFocus();
        txtalamat.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus_data;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox cmbjurusan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtcaridata;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnim;
    private javax.swing.JTable vtabel;
    // End of variables declaration//GEN-END:variables
}
